# Generated by Django 4.2.9 on 2024-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
