FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# RUN pip install celery==5.2.0 redis

COPY . .

CMD [ "celery", "-A", "tasks", "worker", "--loglevel=info", "--pool=solo" ]
