FROM python:3.9-slim

WORKDIR /app

RUN apt-get update

RUN pip3 install --upgrade pip

# 이거 없으면 Mac에서 JPype1 설치 안됨
RUN apt-get install build-essential -y

COPY ./requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD [ "celery", "-A", "tasks", "worker", "--loglevel=info", "--pool=solo" ]
