version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dp
    networks:
      - dp

    restart:
      on-failure
    depends_on:
      - mysql
      - neo4j

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    networks:
      - dp

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./vol:/var/lib/mysql
    networks:
      - dp
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
  
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - dp
    
  redis-insight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    networks:
      - dp

    restart: always
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: ./
      dockerfile: ./Dockerfile-celery
    
    restart: always
    networks:
      - dp
    depends_on:
      - redis

networks:
  dp:
    driver: bridge