# Generated by Django 5.0.2 on 2024-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_keywords_questions_delete_quizs'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='writedate',
            field=models.DateField(default='2024-03-01'),
            preserve_default=False,
        ),
    ]
