# Generated by Django 4.2.9 on 2024-03-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_writedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='writedate',
            new_name='createDate',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='sentence',
        ),
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.TextField(default='string'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywords',
            name='diary',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='diary.diary'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sentences',
        ),
    ]
