# Generated by Django 4.2.9 on 2024-04-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_rename_writedate_diary_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='imgUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='imgUrl',
            field=models.TextField(null=True),
        ),
    ]
