# Generated by Django 4.2.9 on 2024-07-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_diagrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_question_size', models.IntegerField()),
                ('yes_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrecord', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
