# Generated by Django 4.2.9 on 2024-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diag', '0002_rename_yes_count_diagrecord_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagrecord',
            name='total_question_size',
        ),
    ]
