name: Test Django Before Merge

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  django_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          legacy: true

      - name: Set Environment Variables
        run: |
          sudo echo "${{ secrets.DOT_ENT_DJANGO }}" > .env-django
          sudo echo "${{ secrets.DOT_ENT_MYSQL }}" > .env-mysql
          sudo echo "${{ secrets.DOT_ENT_NEO4J }}" > .env-neo4j
          sudo echo "${{ secrets.DOT_ENT_S3 }}" > .env-s3
          sudo echo "${{ secrets.DOT_ENT_DEEPL }}" > .env-deepl

      - name: Set Docker compose Cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: |
            ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build Containers
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-dev.yml -p dp up -d --build

      - name: Test Django
        run: |
          docker exec dp ./wait-for-services.sh python3 manage.py test

      - name: Shutdown Containers
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-dev.yml -p dp down
